baseURL = "/"
languageCode = "en-us"
title = "Margins of remarque"
canonifyurls = true
theme = "blackandlight"
author = "Autrui Majeur"

pygmentsstyle       = "bw"
pygmentscodefences  = true

[params]
  sitename = "Botched Reference"
  disableWebFonts = false
  
  [[menu.main]]
    name = "О сайте"
    url  = "/about"
[[menu.main]]
    name = "Collections"
    url  = "/collections"
[[menu.main]]
    name = "Resume"
    url  = "/resume"
